# Generated by Django 4.0.6 on 2022-08-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_options_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
